/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVisitorsRouteImport } from './routes/_authenticated/visitors'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedQrRouteImport } from './routes/_authenticated/qr'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedElectionsRouteImport } from './routes/_authenticated/elections'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCookingRouteImport } from './routes/_authenticated/cooking'
import { Route as AuthenticatedComplaintsRouteImport } from './routes/_authenticated/complaints'
import { Route as AuthenticatedBuspassRouteImport } from './routes/_authenticated/buspass'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedAiInsightsRouteImport } from './routes/_authenticated/ai-insights'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisitorsRoute = AuthenticatedVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrRoute = AuthenticatedQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedElectionsRoute = AuthenticatedElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCookingRoute = AuthenticatedCookingRouteImport.update({
  id: '/cooking',
  path: '/cooking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplaintsRoute = AuthenticatedComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuspassRoute = AuthenticatedBuspassRouteImport.update({
  id: '/buspass',
  path: '/buspass',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiInsightsRoute = AuthenticatedAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/buspass': typeof AuthenticatedBuspassRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/cooking': typeof AuthenticatedCookingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/elections': typeof AuthenticatedElectionsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qr': typeof AuthenticatedQrRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/buspass': typeof AuthenticatedBuspassRoute
  '/complaints': typeof AuthenticatedComplaintsRoute
  '/cooking': typeof AuthenticatedCookingRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/elections': typeof AuthenticatedElectionsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/qr': typeof AuthenticatedQrRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/visitors': typeof AuthenticatedVisitorsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/ai-insights': typeof AuthenticatedAiInsightsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/buspass': typeof AuthenticatedBuspassRoute
  '/_authenticated/complaints': typeof AuthenticatedComplaintsRoute
  '/_authenticated/cooking': typeof AuthenticatedCookingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/elections': typeof AuthenticatedElectionsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/qr': typeof AuthenticatedQrRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/visitors': typeof AuthenticatedVisitorsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai-insights'
    | '/announcements'
    | '/attendance'
    | '/buspass'
    | '/complaints'
    | '/cooking'
    | '/dashboard'
    | '/elections'
    | '/expenses'
    | '/notifications'
    | '/profile'
    | '/qr'
    | '/reports'
    | '/settings'
    | '/students'
    | '/visitors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai-insights'
    | '/announcements'
    | '/attendance'
    | '/buspass'
    | '/complaints'
    | '/cooking'
    | '/dashboard'
    | '/elections'
    | '/expenses'
    | '/notifications'
    | '/profile'
    | '/qr'
    | '/reports'
    | '/settings'
    | '/students'
    | '/visitors'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/ai-insights'
    | '/_authenticated/announcements'
    | '/_authenticated/attendance'
    | '/_authenticated/buspass'
    | '/_authenticated/complaints'
    | '/_authenticated/cooking'
    | '/_authenticated/dashboard'
    | '/_authenticated/elections'
    | '/_authenticated/expenses'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/qr'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/visitors'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visitors': {
      id: '/_authenticated/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AuthenticatedVisitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr': {
      id: '/_authenticated/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof AuthenticatedQrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/elections': {
      id: '/_authenticated/elections'
      path: '/elections'
      fullPath: '/elections'
      preLoaderRoute: typeof AuthenticatedElectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cooking': {
      id: '/_authenticated/cooking'
      path: '/cooking'
      fullPath: '/cooking'
      preLoaderRoute: typeof AuthenticatedCookingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/complaints': {
      id: '/_authenticated/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AuthenticatedComplaintsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buspass': {
      id: '/_authenticated/buspass'
      path: '/buspass'
      fullPath: '/buspass'
      preLoaderRoute: typeof AuthenticatedBuspassRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-insights': {
      id: '/_authenticated/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AuthenticatedAiInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiInsightsRoute: typeof AuthenticatedAiInsightsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedBuspassRoute: typeof AuthenticatedBuspassRoute
  AuthenticatedComplaintsRoute: typeof AuthenticatedComplaintsRoute
  AuthenticatedCookingRoute: typeof AuthenticatedCookingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedElectionsRoute: typeof AuthenticatedElectionsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQrRoute: typeof AuthenticatedQrRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedVisitorsRoute: typeof AuthenticatedVisitorsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiInsightsRoute: AuthenticatedAiInsightsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedBuspassRoute: AuthenticatedBuspassRoute,
  AuthenticatedComplaintsRoute: AuthenticatedComplaintsRoute,
  AuthenticatedCookingRoute: AuthenticatedCookingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedElectionsRoute: AuthenticatedElectionsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQrRoute: AuthenticatedQrRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedVisitorsRoute: AuthenticatedVisitorsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
