/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVisitorsRouteImport } from './routes/app.visitors'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppElectionsRouteImport } from './routes/app.elections'
import { Route as AppDutiesRouteImport } from './routes/app.duties'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppComplaintsRouteImport } from './routes/app.complaints'
import { Route as AppBusPassRouteImport } from './routes/app.bus-pass'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAnnouncementsRouteImport } from './routes/app.announcements'
import { Route as AppAiInsightsRouteImport } from './routes/app.ai-insights'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitorsRoute = AppVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppElectionsRoute = AppElectionsRouteImport.update({
  id: '/elections',
  path: '/elections',
  getParentRoute: () => AppRoute,
} as any)
const AppDutiesRoute = AppDutiesRouteImport.update({
  id: '/duties',
  path: '/duties',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppBusPassRoute = AppBusPassRouteImport.update({
  id: '/bus-pass',
  path: '/bus-pass',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAnnouncementsRoute = AppAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/bus-pass': typeof AppBusPassRoute
  '/app/complaints': typeof AppComplaintsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/duties': typeof AppDutiesRoute
  '/app/elections': typeof AppElectionsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/visitors': typeof AppVisitorsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/bus-pass': typeof AppBusPassRoute
  '/app/complaints': typeof AppComplaintsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/duties': typeof AppDutiesRoute
  '/app/elections': typeof AppElectionsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/visitors': typeof AppVisitorsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/announcements': typeof AppAnnouncementsRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/bus-pass': typeof AppBusPassRoute
  '/app/complaints': typeof AppComplaintsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/duties': typeof AppDutiesRoute
  '/app/elections': typeof AppElectionsRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/payments': typeof AppPaymentsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/students': typeof AppStudentsRoute
  '/app/visitors': typeof AppVisitorsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ai-insights'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/bus-pass'
    | '/app/complaints'
    | '/app/dashboard'
    | '/app/duties'
    | '/app/elections'
    | '/app/expenses'
    | '/app/payments'
    | '/app/reports'
    | '/app/students'
    | '/app/visitors'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ai-insights'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/bus-pass'
    | '/app/complaints'
    | '/app/dashboard'
    | '/app/duties'
    | '/app/elections'
    | '/app/expenses'
    | '/app/payments'
    | '/app/reports'
    | '/app/students'
    | '/app/visitors'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ai-insights'
    | '/app/announcements'
    | '/app/attendance'
    | '/app/bus-pass'
    | '/app/complaints'
    | '/app/dashboard'
    | '/app/duties'
    | '/app/elections'
    | '/app/expenses'
    | '/app/payments'
    | '/app/reports'
    | '/app/students'
    | '/app/visitors'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visitors': {
      id: '/app/visitors'
      path: '/visitors'
      fullPath: '/app/visitors'
      preLoaderRoute: typeof AppVisitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/elections': {
      id: '/app/elections'
      path: '/elections'
      fullPath: '/app/elections'
      preLoaderRoute: typeof AppElectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/duties': {
      id: '/app/duties'
      path: '/duties'
      fullPath: '/app/duties'
      preLoaderRoute: typeof AppDutiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/complaints': {
      id: '/app/complaints'
      path: '/complaints'
      fullPath: '/app/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bus-pass': {
      id: '/app/bus-pass'
      path: '/bus-pass'
      fullPath: '/app/bus-pass'
      preLoaderRoute: typeof AppBusPassRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/announcements': {
      id: '/app/announcements'
      path: '/announcements'
      fullPath: '/app/announcements'
      preLoaderRoute: typeof AppAnnouncementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-insights': {
      id: '/app/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAnnouncementsRoute: typeof AppAnnouncementsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBusPassRoute: typeof AppBusPassRoute
  AppComplaintsRoute: typeof AppComplaintsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDutiesRoute: typeof AppDutiesRoute
  AppElectionsRoute: typeof AppElectionsRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppVisitorsRoute: typeof AppVisitorsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAnnouncementsRoute: AppAnnouncementsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBusPassRoute: AppBusPassRoute,
  AppComplaintsRoute: AppComplaintsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDutiesRoute: AppDutiesRoute,
  AppElectionsRoute: AppElectionsRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppPaymentsRoute: AppPaymentsRoute,
  AppReportsRoute: AppReportsRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppVisitorsRoute: AppVisitorsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
